### ISSUE TITLE
!!!Spontaneous switching of the miner to other pools and coins

### ISSUE THREAD

**Issue by EVGENY1777** [PhoenixMinerDevTeam/PhoenixMiner#22] opened 2021-03-23 18:16 UTC
Today, two rigs were switched spontaneously -
one rig switched to ETC, 
the other to nanopool.  

What's going on???  
switched to TRM.... because this isn't the first time this has happened...
logs-below. 
https://transfiles.ru/dqax

**Comment by PhoenixMinerDevTeam** [comment] 2021-03-26 08:40
Duplicate of issue #19

**Closed by PhoenixMinerDevTeam** 2021-03-26 08:40 UTC
